<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Auth_item_model extends CI_Model
{

    public $table = 'auth_item';
    public $id = 'id_aunt';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function FunctionName($value='')
    {
        $this->db->where('tipe', $no);
        $data = $this->db->get($table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_aunt', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('tipe', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_aunt', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('tipe', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Auth_item_model.php */
/* Location: ./application/models/Auth_item_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-03-13 17:08:49 */
/* http://harviacode.com */