<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Catatan_model extends CI_Model
{

    public $table = 'catatan';
    public $id = 'id_catatan';
    public $idk = 'id_kelas_siswa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_catatan,id_kelas_siswa,kelakuan,kerajinan,kebersihan,izin,sakit,alpa,catatan');
        $this->datatables->from('catatan');
        //add this line for join
        //$this->datatables->join('table2', 'catatan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/catatan/read/$1'),'Read')." | ".anchor(site_url('admin/catatan/update/$1'),'Update')." | ".anchor(site_url('admin/catatan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_catatan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id
    function get_by_idk($id)
    {
        $this->db->where($this->idk, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_catatan', $q);
	$this->db->or_like('id_kelas_siswa', $q);
	$this->db->or_like('kelakuan', $q);
	$this->db->or_like('kerajinan', $q);
	$this->db->or_like('kebersihan', $q);
	$this->db->or_like('izin', $q);
	$this->db->or_like('sakit', $q);
	$this->db->or_like('alpa', $q);
	$this->db->or_like('catatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_catatan', $q);
	$this->db->or_like('id_kelas_siswa', $q);
	$this->db->or_like('kelakuan', $q);
	$this->db->or_like('kerajinan', $q);
	$this->db->or_like('kebersihan', $q);
	$this->db->or_like('izin', $q);
	$this->db->or_like('sakit', $q);
	$this->db->or_like('alpa', $q);
	$this->db->or_like('catatan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Catatan_model.php */
/* Location: ./application/models/Catatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-18 03:56:46 */
/* http://harviacode.com */