<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_santri_model extends CI_Model
{

    public $table = 'data_santri';
    public $id = 'id_santri';
    public $idu = 'id_user';
    public $nid = 'nomor_induk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($id) {
        $this->datatables->select('id_santri,nama_lengkap,nama_panggilan,nomor_induk,tempat_lahir,tanggal_lahir,anak_ke,nama_ayah,nama_ibu,pekerjaan_ayah,pekerjaan_ibu,alamat_ortu,telepon_ortu,kelurahan,kecamatan,kota,provinsi,foto,tanggal_masuk');
        $this->datatables->from('data_santri');
        //add this line for join
        //$this->datatables->join('table2', 'data_santri.field = table2.field');
        if ($id>1) {
            $this->datatables->where($this->idu, $id);
        }
        $this->datatables->add_column('action', 
            anchor(site_url('admin/data_santri/read/$1'),'Read')
            ." | ".anchor(site_url('admin/data_santri/update/$1'),'Update')
            // ." | ".anchor(site_url('admin/data_santri/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"')
            , 'id_santri');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_nid($id)
    {
        $this->db->where($this->nid, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_idrow()
    {
        $this->db->limit(1);
        $this->db->order_by($this->nid, $this->order);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_santri', $q);
    $this->db->or_like('nama_lengkap', $q);
    $this->db->or_like('nama_panggilan', $q);
    $this->db->or_like('nomor_induk', $q);
    $this->db->or_like('tempat_lahir', $q);
    $this->db->or_like('tanggal_lahir', $q);
    $this->db->or_like('anak_ke', $q);
    $this->db->or_like('nama_ayah', $q);
    $this->db->or_like('nama_ibu', $q);
    $this->db->or_like('pekerjaan_ayah', $q);
    $this->db->or_like('pekerjaan_ibu', $q);
    $this->db->or_like('alamat_ortu', $q);
    $this->db->or_like('telepon_ortu', $q);
    $this->db->or_like('kelurahan', $q);
    $this->db->or_like('kecamatan', $q);
    $this->db->or_like('kota', $q);
    $this->db->or_like('provinsi', $q);
    $this->db->or_like('foto', $q);
    $this->db->or_like('tanggal_masuk', $q);
    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_santri', $q);
    $this->db->or_like('nama_lengkap', $q);
    $this->db->or_like('nama_panggilan', $q);
    $this->db->or_like('nomor_induk', $q);
    $this->db->or_like('tempat_lahir', $q);
    $this->db->or_like('tanggal_lahir', $q);
    $this->db->or_like('anak_ke', $q);
    $this->db->or_like('nama_ayah', $q);
    $this->db->or_like('nama_ibu', $q);
    $this->db->or_like('pekerjaan_ayah', $q);
    $this->db->or_like('pekerjaan_ibu', $q);
    $this->db->or_like('alamat_ortu', $q);
    $this->db->or_like('telepon_ortu', $q);
    $this->db->or_like('kelurahan', $q);
    $this->db->or_like('kecamatan', $q);
    $this->db->or_like('kota', $q);
    $this->db->or_like('provinsi', $q);
    $this->db->or_like('foto', $q);
    $this->db->or_like('tanggal_masuk', $q);
    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function delete_kelas_santri($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete("kelas_santri");
    }

    function delete_nilai_santri($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete("nilai_santri");
    }

}

/* End of file Data_santri_model.php */
/* Location: ./application/models/Data_santri_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-01 15:13:19 */
/* http://harviacode.com */