<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_kelas_model extends CI_Model
{

    public $table = 'data_kelas';
    public $id = 'id_kelas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('data_kelas.id_kelas,nama_kelas,data_kelas.id_jenjang,data_jenjang.nama_jenjang');
        $this->datatables->from('data_kelas');
        //add this line for join
        $this->datatables->join('data_jenjang', 'data_kelas.id_jenjang = data_jenjang.id_jenjang');
        $this->datatables->add_column('action', anchor(site_url('admin/data_kelas/read/$1'),'Read')." | ".anchor(site_url('admin/data_kelas/update/$1'),'Update')." | ".anchor(site_url('admin/data_kelas/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_kelas');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kelas', $q);
	$this->db->or_like('nama_kelas', $q);
	$this->db->or_like('id_jenjang', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kelas', $q);
	$this->db->or_like('nama_kelas', $q);
	$this->db->or_like('id_jenjang', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_kelas_model.php */
/* Location: ./application/models/Data_kelas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-01 15:11:28 */
/* http://harviacode.com */