<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_ustadz_model extends CI_Model
{

    public $table = 'data_ustadz';
    public $id = 'id_ustadz';
    public $idu = 'id_user';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($id) {
        $this->datatables->select('id_ustadz,nip,nama_ustadz,status,jk,tempat_lahir,tgl_lahir,alamat,nama_ayah,nama_ibu,alamat_ortu,foto,tgl_masuk');
        $this->datatables->from('data_ustadz');
        //add this line for join
        //$this->datatables->join('table2', 'data_ustadz.field = table2.field');
        if ($id>1) {
            $this->datatables->where($this->idu, $id);
        }
        $this->datatables->add_column('action', anchor(site_url('admin/data_ustadz/read/$1'),'Read')." | ".anchor(site_url('admin/data_ustadz/update/$1'),'Update')." | ".anchor(site_url('admin/data_ustadz/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_ustadz');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_ustadz', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('nama_ustadz', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('nama_ayah', $q);
	$this->db->or_like('nama_ibu', $q);
	$this->db->or_like('alamat_ortu', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('tgl_masuk', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_ustadz', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('nama_ustadz', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('nama_ayah', $q);
	$this->db->or_like('nama_ibu', $q);
	$this->db->or_like('alamat_ortu', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('tgl_masuk', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_ustadz_model.php */
/* Location: ./application/models/Data_ustadz_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-01 15:14:13 */
/* http://harviacode.com */