<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_file_model extends CI_Model
{

    public $table = 'data_file';
    public $id = 'id_file';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_file,judul,deskripsi,file,tgl_upload');
        $this->datatables->from('data_file');
        //add this line for join
        //$this->datatables->join('table2', 'data_file.field = table2.field');
        $this->datatables->add_column('download', 
            anchor(site_url('assets/file/$1'),'download'), 'file');
        $this->datatables->add_column('action', 
            anchor(site_url('admin/data_file/read/$1'),'Read')." | ".
            anchor(site_url('admin/data_file/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'
        ), 'id_file');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_file', $q);
	$this->db->or_like('judul', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('file', $q);
	$this->db->or_like('tgl_upload', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_file', $q);
	$this->db->or_like('judul', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('file', $q);
	$this->db->or_like('tgl_upload', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_file_model.php */
/* Location: ./application/models/Data_file_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-20 09:24:47 */
/* http://harviacode.com */