<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kelas_mapel_model extends CI_Model
{

    public $table = 'kelas_mapel';
    public $table2 = 'view_kelas_mapel';
    public $id = 'id_klsmapel';
    public $id2 = 'id_klstpq';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($srt) {
        $this->datatables->select('id_klsmapel,id_mapel,nama_mapel,nama_jenis_mapel,id_klstpq');
        $this->datatables->from('view_kelas_mapel');
        //add this line for join
        //$this->datatables->join('table2', 'kelas_mapel.field = table2.field');
        $this->datatables->where('id_klstpq', $srt, '=' );
        $this->datatables->add_column('action', anchor(site_url('admin/kelas_mapel/update/$1'),'Update')." | ".anchor(site_url('admin/kelas_mapel/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_klsmapel');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all
    function get_all_where($id)
    {
        $this->db->where($this->id2, $id);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table2)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_klsmapel', $q);
	$this->db->or_like('id_mapel', $q);
	$this->db->or_like('id_klstpq', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_klsmapel', $q);
	$this->db->or_like('id_mapel', $q);
	$this->db->or_like('id_klstpq', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kelas_mapel_model.php */
/* Location: ./application/models/Kelas_mapel_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-20 14:41:08 */
/* http://harviacode.com */