<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kelas_tpq_model extends CI_Model
{

    public $table = 'kelas_tpq';
    public $id = 'id_klstpq';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_klstpq,id_tpq,id_kelas,id_tahun_ajaran,semester');
        $this->datatables->from('kelas_tpq');
        //add this line for join
        //$this->datatables->join('table2', 'kelas_tpq.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/kelas_tpq/read/$1'),'Read')." | ".anchor(site_url('admin/kelas_tpq/update/$1'),'Update')." | ".anchor(site_url('admin/kelas_tpq/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_klstpq');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_data($id_tpq,$id_kelas,$id_tahun_ajaran,$semester)
    {
        $this->db->where('id_tpq', $id_tpq);
        $this->db->where('id_kelas', $id_kelas);
        $this->db->where('id_tahun_ajaran', $id_tahun_ajaran);
        $this->db->where('semester', $semester);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_klstpq', $q);
	$this->db->or_like('id_tpq', $q);
	$this->db->or_like('id_kelas', $q);
	$this->db->or_like('id_tahun_ajaran', $q);
	$this->db->or_like('semester', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_klstpq', $q);
	$this->db->or_like('id_tpq', $q);
	$this->db->or_like('id_kelas', $q);
	$this->db->or_like('id_tahun_ajaran', $q);
	$this->db->or_like('semester', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kelas_tpq_model.php */
/* Location: ./application/models/Kelas_tpq_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-01 15:16:41 */
/* http://harviacode.com */