<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class View_kelas_model extends CI_Model
{

    public $table = 'view_kelas';
    public $table2 = 'view_kelas_santri';
    public $table3 = 'view_nilai';
    public $table4 = 'view_grafik_nilai';
    public $id = 'id_klstpq';
    public $idu = 'id_tpq';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($id) {
        $this->datatables->select('id_klstpq,id_tpq,nama_tpq,id_kelas,nama_kelas,id_jenjang,nama_jenjang,id_tahun_ajaran,nama_ajaran,status,semester');
        $this->datatables->from('view_kelas');
        if ($id>1) {
            $this->datatables->where($this->idu, $id);
        }
        //add this line for join
        //$this->datatables->join('table2', 'view_kelas.field = table2.field');
        $this->datatables->add_column('action', 
            anchor(site_url('admin/view_kelas/read/$1'),'Daftar Siswa')//." | ".
            // anchor(site_url('admin/view_kelas/update/$1'),'Update')." | ".
            // anchor(site_url('admin/view_kelas/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"')
        ,'');
        return $this->datatables->generate();
    }

    // get all
    function get_all($id)
    {
        $this->db->order_by($this->id, $this->order);
        if ($id>0) {
            $this->db->where($this->idu, $id);
        }
        return $this->db->get($this->table)->result();
    }

    function get_all_versantri($id)
    {
        $this->db->where("nomor_induk", $id);
        return $this->db->get($this->table2)->result();
    }

    function get_all_grafik($id)
    {
        $this->db->where("nomor_induk", $id);
        return $this->db->get($this->table4)->result();
    }

    function get_all_nilai($id)
    {
        $this->db->where("id_kelas_siswa", $id);
        return $this->db->get($this->table3)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('', $q);
	$this->db->or_like('id_klstpq', $q);
	$this->db->or_like('id_tpq', $q);
	$this->db->or_like('nama_tpq', $q);
	$this->db->or_like('id_kelas', $q);
	$this->db->or_like('nama_kelas', $q);
	$this->db->or_like('id_jenjang', $q);
	$this->db->or_like('nama_jenjang', $q);
	$this->db->or_like('id_tahun_ajaran', $q);
	$this->db->or_like('nama_ajaran', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('semester', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('', $q);
	$this->db->or_like('id_klstpq', $q);
	$this->db->or_like('id_tpq', $q);
	$this->db->or_like('nama_tpq', $q);
	$this->db->or_like('id_kelas', $q);
	$this->db->or_like('nama_kelas', $q);
	$this->db->or_like('id_jenjang', $q);
	$this->db->or_like('nama_jenjang', $q);
	$this->db->or_like('id_tahun_ajaran', $q);
	$this->db->or_like('nama_ajaran', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('semester', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file View_kelas_model.php */
/* Location: ./application/models/View_kelas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-09 09:43:01 */
/* http://harviacode.com */