<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dashboard extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->authclass->check_isvalidated(base_url());
        // $this->load->model('Produk_model');
        // $this->load->model('Users_model');
        // $this->load->model('Transaksi_model');
    }

    public function index()
    {
        // $row = $this->Produk_model->get_all();
        // $row2 = $this->Users_model->get_all();
        // $row3 = $this->Transaksi_model->get_all();
        // $row4 = $this->Transaksi_model->get_allp();
        $data = array(
            'title' => 'Dashboard',
            // 'total_produk' => count($row),
            // 'total_user' => count($row2),
            // 'total_tran' => count($row3),
            // 'total_pen' => $row4->total,
        );

        $this->template->load('template','admin/dashboard', $data);
    }

    
}

/* End of file Kategori.php */
/* Location: ./application/controllers/Kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-02-07 01:38:10 */
/* http://harviacode.com */