<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_kelas extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Data_kelas_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $data = array('title' => 'data_kelas');
        $this->template->load('template','admin/data_kelas/data_kelas_list', $data);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Data_kelas_model->json();
    }

    public function read($id) 
    {
        $row = $this->Data_kelas_model->get_by_id($id);
        if ($row) {
            $data = array(
                'title' => 'Read',
		'id_kelas' => $row->id_kelas,
		'nama_kelas' => $row->nama_kelas,
		'id_jenjang' => $row->id_jenjang,
	    );
            $this->template->load('template','admin/data_kelas/data_kelas_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/data_kelas'));
        }
    }

    public function create() 
    {
        $data = array(
            'title' => 'Create',
            'button' => 'Create',
            'action' => site_url('admin/data_kelas/create_action'),
	    'id_kelas' => set_value('id_kelas'),
	    'nama_kelas' => set_value('nama_kelas'),
	    'id_jenjang' => set_value('id_jenjang'),
	);
        $this->template->load('template','admin/data_kelas/data_kelas_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_kelas' => $this->input->post('nama_kelas',TRUE),
		'id_jenjang' => $this->input->post('id_jenjang',TRUE),
	    );

            $this->Data_kelas_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/data_kelas'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Data_kelas_model->get_by_id($id);

        if ($row) {
            $data = array(
                'title' => 'Update',
                'button' => 'Update',
                'action' => site_url('admin/data_kelas/update_action'),
		'id_kelas' => set_value('id_kelas', $row->id_kelas),
		'nama_kelas' => set_value('nama_kelas', $row->nama_kelas),
		'id_jenjang' => set_value('id_jenjang', $row->id_jenjang),
	    );
            $this->template->load('template','admin/data_kelas/data_kelas_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/data_kelas'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_kelas', TRUE));
        } else {
            $data = array(
		'nama_kelas' => $this->input->post('nama_kelas',TRUE),
		'id_jenjang' => $this->input->post('id_jenjang',TRUE),
	    );

            $this->Data_kelas_model->update($this->input->post('id_kelas', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/data_kelas'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Data_kelas_model->get_by_id($id);

        if ($row) {
            $this->Data_kelas_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/data_kelas'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/data_kelas'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_kelas', 'nama kelas', 'trim|required');
	$this->form_validation->set_rules('id_jenjang', 'id jenjang', 'trim|required');

	$this->form_validation->set_rules('id_kelas', 'id_kelas', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Data_kelas.php */
/* Location: ./application/controllers/Data_kelas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-01 15:11:28 */
/* http://harviacode.com */