<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_jenjang extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Data_jenjang_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $data = array('title' => 'data_jenjang');
        $this->template->load('template','admin/data_jenjang/data_jenjang_list', $data);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Data_jenjang_model->json();
    }

    public function read($id) 
    {
        $row = $this->Data_jenjang_model->get_by_id($id);
        if ($row) {
            $data = array(
                'title' => 'Read',
		'id_jenjang' => $row->id_jenjang,
		'nama_jenjang' => $row->nama_jenjang,
	    );
            $this->template->load('template','admin/data_jenjang/data_jenjang_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/data_jenjang'));
        }
    }

    public function create() 
    {
        $data = array(
            'title' => 'Create',
            'button' => 'Create',
            'action' => site_url('admin/data_jenjang/create_action'),
	    'id_jenjang' => set_value('id_jenjang'),
	    'nama_jenjang' => set_value('nama_jenjang'),
	);
        $this->template->load('template','admin/data_jenjang/data_jenjang_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_jenjang' => $this->input->post('nama_jenjang',TRUE),
	    );

            $this->Data_jenjang_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/data_jenjang'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Data_jenjang_model->get_by_id($id);

        if ($row) {
            $data = array(
                'title' => 'Update',
                'button' => 'Update',
                'action' => site_url('admin/data_jenjang/update_action'),
		'id_jenjang' => set_value('id_jenjang', $row->id_jenjang),
		'nama_jenjang' => set_value('nama_jenjang', $row->nama_jenjang),
	    );
            $this->template->load('template','admin/data_jenjang/data_jenjang_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/data_jenjang'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_jenjang', TRUE));
        } else {
            $data = array(
		'nama_jenjang' => $this->input->post('nama_jenjang',TRUE),
	    );

            $this->Data_jenjang_model->update($this->input->post('id_jenjang', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/data_jenjang'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Data_jenjang_model->get_by_id($id);

        if ($row) {
            $this->Data_jenjang_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/data_jenjang'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/data_jenjang'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_jenjang', 'nama jenjang', 'trim|required');

	$this->form_validation->set_rules('id_jenjang', 'id_jenjang', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Data_jenjang.php */
/* Location: ./application/controllers/Data_jenjang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-01 15:11:06 */
/* http://harviacode.com */