<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Grafik_nilai extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Data_tpq_model');
        $this->load->model('View_kelas_model');
        $this->load->model('Kelas_santri_model');
        $this->load->library('form_validation');        
	   $this->load->library('datatables');
    }

    public function index()
    {
        $lvl = $this->session->userdata("lvl");        
        if ($lvl=="Superadmin" || $lvl=="Admin") {
            $data = array('title' => 'data_santri');
        } elseif ($lvl=="User") {
            $id = $this->session->userdata("user_id"); 
            $auth_item = $this->View_kelas_model->get_all_grafik($id);
            $dar = '';
            $rat = '';
            foreach ($auth_item as $key => $value) {
                $dar .=  "'Kelas ".$value->nama_kelas.' '.$value->semester."',";
                $rat .=  $value->rata.",";
            }
            $data = array(
                'title' => 'Grafik Nilai',
                'dar' => $dar,
                'rat' => $rat,
                'yes' => false,
            );
        }
        
        $this->template->load('template','admin/rekap_nilai/grafik_nilai', $data);
    } 
    

    public function read($id) 
    {
        $auth_item = $this->View_kelas_model->get_all_grafik($id);
        $dar = '';
        $rat = '';
        foreach ($auth_item as $key => $value) {
            $dar .=  "'Kelas ".$value->nama_kelas.' '.$value->semester."',";
            $rat .=  $value->rata.",";
        }
        $data = array(
            'title' => 'Grafik Nilai',
            'dar' => $dar,
            'rat' => $rat,
            'yes' => true,
        );
        $this->template->load('template','admin/rekap_nilai/grafik_nilai', $data);
    }



}

/* End of file rekap_nilai.php */
/* Location: ./application/controllers/rekap_nilai.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-09 09:43:01 */
/* http://harviacode.com */