<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kelas_mapel extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kelas_mapel_model');
        $this->load->library('form_validation');        
	   $this->load->library('datatables');
    }

    public function index($i="")
    {
        $data = array(
            'title' => 'Kelas Mapel',
            'srt' => $i
        );
        $this->template->load('template','admin/kelas_mapel/kelas_mapel_list', $data);
    } 
    
    public function json() {
        $srt = $this->input->post('srt',TRUE);
        header('Content-Type: application/json');
        echo $this->Kelas_mapel_model->json($srt);
    }

    public function read($id) 
    {
        $row = $this->Kelas_mapel_model->get_by_id($id);
        if ($row) {
            $data = array(
                'title' => 'Read',
		'id_klsmapel' => $row->id_klsmapel,
		'id_mapel' => $row->id_mapel,
		'id_klstpq' => $row->id_klstpq,
	    );
            $this->template->load('template','admin/kelas_mapel/kelas_mapel_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/kelas_mapel'));
        }
    }

    public function create($srt) 
    {
        $data = array(
            'title' => 'Create',
            'button' => 'Create',
            'action' => site_url('admin/kelas_mapel/create_action'),
	    'id_klsmapel' => set_value('id_klsmapel'),
	    'id_mapel' => set_value('id_mapel'),
	    'id_klstpq' => $srt,
	);
        $this->template->load('template','admin/kelas_mapel/kelas_mapel_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_mapel' => $this->input->post('id_mapel',TRUE),
		'id_klstpq' => $this->input->post('id_klstpq',TRUE),
	    );

            $this->Kelas_mapel_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/kelas_mapel/index/'.$data['id_klstpq']));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Kelas_mapel_model->get_by_id($id);

        if ($row) {
            $data = array(
                'title' => 'Update',
                'button' => 'Update',
                'action' => site_url('admin/kelas_mapel/update_action'),
		'id_klsmapel' => set_value('id_klsmapel', $row->id_klsmapel),
		'id_mapel' => set_value('id_mapel', $row->id_mapel),
		'id_klstpq' => set_value('id_klstpq', $row->id_klstpq),
	    );
            $this->template->load('template','admin/kelas_mapel/kelas_mapel_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/kelas_mapel'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_klsmapel', TRUE));
        } else {
            $data = array(
		'id_mapel' => $this->input->post('id_mapel',TRUE),
		'id_klstpq' => $this->input->post('id_klstpq',TRUE),
	    );

            $this->Kelas_mapel_model->update($this->input->post('id_klsmapel', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/kelas_mapel/index/'.$data['id_klstpq']));
        }
    }
    
    public function delete($id,$id_klstpq) 
    {
        $row = $this->Kelas_mapel_model->get_by_id($id);

        if ($row) {
            $this->Kelas_mapel_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/kelas_mapel/index/'.$id_klstpq));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/kelas_mapel/index/'.$id_klstpq));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_mapel', 'id mapel', 'trim|required');
	$this->form_validation->set_rules('id_klstpq', 'id klstpq', 'trim|required');

	$this->form_validation->set_rules('id_klsmapel', 'id_klsmapel', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kelas_mapel.php */
/* Location: ./application/controllers/Kelas_mapel.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-20 14:41:08 */
/* http://harviacode.com */