<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tes extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tes_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $data = array('title' => 'tes');
        $this->template->load('template','admin/tes/tes_list', $data);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tes_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tes_model->get_by_id($id);
        if ($row) {
            $data = array(
                'title' => 'Read',
		'id' => $row->id,
		'judul' => $row->judul,
		'deskripsi' => $row->deskripsi,
		'images' => $row->images,
	    );
            $this->template->load('template','admin/tes/tes_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/tes'));
        }
    }

    public function create() 
    {
        $data = array(
            'title' => 'Create',
            'button' => 'Create',
            'action' => site_url('admin/tes/create_action'),
	    'id' => set_value('id'),
	    'judul' => set_value('judul'),
	    'deskripsi' => set_value('deskripsi'),
	    'images' => set_value('images'),
	);
        $this->template->load('template','admin/tes/tes_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'judul' => $this->input->post('judul',TRUE),
		'deskripsi' => $this->input->post('deskripsi',TRUE),
		'images' => $this->input->post('images',TRUE),
	    );

            $this->Tes_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/tes'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tes_model->get_by_id($id);

        if ($row) {
            $data = array(
                'title' => 'Update',
                'button' => 'Update',
                'action' => site_url('admin/tes/update_action'),
		'id' => set_value('id', $row->id),
		'judul' => set_value('judul', $row->judul),
		'deskripsi' => set_value('deskripsi', $row->deskripsi),
		'images' => set_value('images', $row->images),
	    );
            $this->template->load('template','admin/tes/tes_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/tes'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'judul' => $this->input->post('judul',TRUE),
		'deskripsi' => $this->input->post('deskripsi',TRUE),
		'images' => $this->input->post('images',TRUE),
	    );

            $this->Tes_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/tes'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tes_model->get_by_id($id);

        if ($row) {
            $this->Tes_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/tes'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/tes'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('judul', 'judul', 'trim|required');
	$this->form_validation->set_rules('deskripsi', 'deskripsi', 'trim|required');
	$this->form_validation->set_rules('images', 'images', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tes.php */
/* Location: ./application/controllers/Tes.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-09 05:59:20 */
/* http://harviacode.com */